### ISSUE TITLE
Allow SkeletonGridLoader to accept a custom childAspectRatio

### ISSUE THREAD

**Issue by ricbermo** [lhamycodes/skeleton_loader#2]
Hello there,

I'm trying to use this package but the `SkeletonGridLoader` doesn't accept a custom `childAspectRatio` making the "loaders" just squared. IMHO, accepting the `childAspectRatio` would allow us (developers) to create this kind of skeletons

![image](https://user-images.githubusercontent.com/2601363/110358709-b0d96e80-800a-11eb-9696-45d6c1f82069.png)

I'm more that happy to contribute if u think this would be a good addition.

Thanks,

**Comment by lhamycodes** [comment]
Hello @ricbermo, thanks for reaching out to me with this issue.

As of now, I've released a new version of this package that has support for childAspectRatio on SkeletonGridLoader.

Thank you.
